export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const SAVE_ALL_TASKS = 'SAVE_ALL_TASKS';
export const TOGGLE_FORM_VISIBILITY = 'TOGGLE_FORM_VISIBILITY';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_TASK_TITLE = 'SET_TASK_TITLE';
export const TOGGLE_TASK_TITLE_INPUT = 'TOGGLE_TASK_TITLE_INPUT';
export const SET_POST_SUCCESS = 'SET_POST_SUCCESS';